image: lukasheinrich/recast_cvmfs_assisted


stages:
  - setup
  - build
  - test

setup:
  stage: setup
  tags:
    - cvmfs
  script:
    - bash
    - pwd;ls
    - cd ..
    - pwd; ls
    - source FactoryTools/util/setup_CI.sh
    - git clone https://github.com/lawrenceleejr/Ext_RestFrames.git; cd Ext_RestFrames; git checkout v1.7; git checkout -b v1.7; cd ..
    - rc checkout_pkg svn+ssh://atlzerol@svn.cern.ch/reps/atlasoff/PhysicsAnalysis/SUSYPhys/SUSYTools/tags/SUSYTools-00-08-02 SUSYTools;
    - rc checkout SUSYTools/doc/packages.txt;
    - git clone https://github.com/UCATLAS/xAODAnaHelpers.git; cd xAODAnaHelpers; git checkout 630919c55078d543f91e1dee12175a1c4783941e;  git checkout -b localRJbranch; cd ..;
    - rc checkout_pkg svn+ssh://atlzerol@svn.cern.ch/reps/atlasinst/Institutes/LBNL/AnalysisToolsRunII/CommonTools/trunk/ CommonTools; cd CommonTools; svn update -r 417222; cd -;

compile:
  stage: build
  tags:
    - cvmfs
  script:
    - rc find_packages
    - rc compile

runmc:
  stage: test
  tags:
    - cvmfs
  script:
    - python FactoryTools/util/run_zl.py  --doOverwrite --nevents 10 --verbosity debug --inputDS /afs/cern.ch/work/r/rsmith/public/factoryToolsSample/
